---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false


# Spine Switches
spine:
  defaults:
    platform: vEOS-lab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: dc1-spine1
      id: 11
      mgmt_ip: 192.168.0.111/24
    - name: dc1-spine2
      id: 12
      mgmt_ip: 192.168.1.112/24
    - name: dc1-spine3
      id: 13
      mgmt_ip: 192.168.0.113/24
    - name: dc1-spine4
      id: 14
      mgmt_ip: 192.168.0.114/24

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65100-65199 # Gives a range which will be auto-assigned
    platform: vEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.102.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4, Ethernet5, Ethernet6] # Leaf uplinks
    uplink_switches: [dc1-spine1, dc1-spine2, dc1-spine3, dc1-spine4] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.103.0/24 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG
  node_groups: 
    - group: mlag1
    # bgp_as is configured automatically from the range, but can be overriden
      nodes:
        - name: dc1-leaf1
          id: 1
          mgmt_ip: 192.168.0.101/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3, Ethernet3]
        - name: dc1-leaf2
          id: 2
          mgmt_ip: 192.168.0.102/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4, Ethernet4]
    - group: mlag2
      bgp_as: 65299 # Overriden automatic allocation for host4/R1 peering
      nodes:
        - name: dc1-leaf3
          id: 3
          mgmt_ip: 192.168.0.103/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5, Ethernet5]
        - name: dc1-leaf4
          id: 4
          mgmt_ip: 192.168.0.104/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6, Ethernet6]
    - group: borderleafs
      bgp_as: 65500 # Overriden automatic allocation for host4/R1 peering
      nodes:
        - name: dc1-borderleaf1
          id: 5
          mgmt_ip: 192.168.0.105/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7, Ethernet7, Ethernet7]
        - name: dc1-borderleaf2
          id: 6
          mgmt_ip: 192.168.0.106/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8, Ethernet8, Ethernet8]



# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1550

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
#dns_domain: atd.lab
#mgmt_interface: Management0
#mgmt_interface_vrf: MGMT
#mgmt_gateway: 192.168.0.1
