---
### group_vars/DC1_NETWORK_SERVICES.yml

tenants:
  - name: MY_FABRIC
    vrfs:
      - name: default
        svis:
          - id: 110
            name: 'Data'
            tags: ["110"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.10.1
            nodes:
              - node: spine1
                ip_address: 10.1.10.2/23
              - node: spine2
                ip_address: 10.1.10.3/23
          - id: 120
            name: 'Voice'
            tags: ["120"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.20.1
            nodes:
              - node: spine1
                ip_address: 10.1.20.2/23
              - node: spine2
                ip_address: 10.1.20.3/23
          - id: 130
            name: 'Guest'
            tags: ["130"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.1.30.1
            nodes:
              - node: spine1
                ip_address: 10.1.30.2/23
              - node: spine2
                ip_address: 10.1.30.3/23
          - id: 210
            name: 'Staff'
            tags: ["210"]
            enabled: true
            ip_virtual_router_addresses:
              - 10.2.10.1
            nodes:
              - node: spine1
                ip_address: 10.2.10.2/23
              - node: spine2
                ip_address: 10.2.10.3/23

