---
# Default gateway used for the management interface
#mgmt_gateway: 172.16.1.1
mgmt_gateway: 192.168.0.5
###If a management vrf is to be used you can define it in the next line, or just ask for default###
mgmt_interface_vrf: default
# Spine switch group
spine:
  # Definition of default values that will be configured to all nodes defined in this group
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # ASN to be used by BGP
    bgp_as: 65100

  # Definition of nodes contained in this group.
  # Specific configuration of device must take place under the node definition. Each node inherits all values defined under 'defaults'
  nodes:
    # Name of the node to be defined (must be consistent with definition in inventory)
    - name: dc1-spine1
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 1
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.111/24

    - name: dc1-spine2
      id: 2
      mgmt_ip: 192.168.1.112/24

    - name: dc1-spine3
      # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
      id: 3
      # Management IP to be assigned to the management interface
      mgmt_ip: 192.168.0.113/24

    - name: dc1-spine4
      id: 4
      mgmt_ip: 192.168.0.114/24

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/26
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 4
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/26
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2', 'dc1-spine3', 'dc1-spine4']
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/24
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.2.64/26
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.3.96/26
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  # If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC1_L3_LEAF1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65001
      nodes:
        # Definition of hostnames under the node_group
        - name: dc1-leaf1
          id: 5
          mgmt_ip: 192.168.0.101/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
            - Ethernet3
            - Ethernet3
        - name: dc1-leaf2
          id: 6
          mgmt_ip: 192.168.0.102/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
            - Ethernet4
            - Ethernet4
    - group: DC1_L3_LEAF2
      bgp_as: 65002
      nodes:
        - name: dc1-leaf3
          id: 7
          mgmt_ip: 192.168.0.103/24
          uplink_switch_interfaces:
            - Ethernet5
            - Ethernet5
            - Ethernet5
            - Ethernet5
        - name: dc1-leaf4
          id: 8
          mgmt_ip: 192.168.0.104/24
          uplink_switch_interfaces:
            - Ethernet6
            - Ethernet6
            - Ethernet6
            - Ethernet6
    - group: DC1_BR_LEAF
      bgp_as: 65500
      nodes:
        - name: dc1-borderleaf1
          id: 9
          mgmt_ip: 192.168.0.105/24
          uplink_switch_interfaces:
            - Ethernet7
            - Ethernet7
            - Ethernet7
            - Ethernet7
        - name: dc1-borderleaf2
          id: 10
          mgmt_ip: 192.168.0.106/24
          uplink_switch_interfaces:
            - Ethernet8
            - Ethernet8
            - Ethernet8
            - Ethernet8
