---
- name: Deploy Configurations to Devices Using CloudVision Portal # (1)!
  hosts: FABRIC
  gather_facts: false
  connection: local
  tasks:

    - name: Provision CVP with AVD configuration
      run_once: true
      delegate_to: localhost
      # https://avd.arista.com/4.10/docs/plugins/Modules_and_action_plugins/cv_workflow.html
      # https://avd.arista.com/4.10/roles/cv_deploy/index.html
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 10.18.128.112
        cv_token: "{{ lookup('file', 'avdtoken') }}"
        cv_submit_workspace: true
        cv_run_change_control: true
        #deploy_to_cv_accept_preview: true
        cv_verify_certs: false
        #cv_skip_missing_devices: true
        #configlet_name_template: "AVD-${hostname}"
        #cv_submit_workspace: true
