---
- name: Deploy Configurations to Devices Using CloudVision Portal # (1)!
  hosts: CLOUDVISION
  gather_facts: false
  connection: local
  tasks:

    - name: Provision CVP with AVD configuration
      run_once: true
      delegate_to: localhost
      # https://avd.arista.com/4.10/docs/plugins/Modules_and_action_plugins/cv_workflow.html
      # https://avd.arista.com/4.10/roles/cv_deploy/index.html
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: www.cv-staging.corp.arista.io
        cv_token: "{{ lookup('file', '../avdtoken') }}"
        cv_run_change_control: false
        deploy_to_cv_accept_preview: true
        #configlet_name_template: "AVD-${hostname}"
        #cv_submit_workspace: true
